version: '2'
services:
  client:
    build:
      context: ./client/
    command: npm start
    stdin_open: true
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    # depends_on:
    #   - server
    ports:
      - "4001:3000"
